import Fastify, { type FastifyInstance, type FastifyServerOptions } from 'fastify';
import { randomUUID } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { createSoulToolDispatcher } from '@do-what/soul';
import { runGit, WorktreeManager } from '@do-what/tools';
import {
  HOST,
  PORT,
  SESSION_TOKEN_PATH,
  STATE_DIR,
  ensureRuntimeDirs,
} from '../config.js';
import { StateStore } from '../db/state-store.js';
import { WorkerClient } from '../db/worker-client.js';
import { createReadConnection } from '../db/read-connection.js';
import { attachAsyncEventPath, EventDispatcher } from '../event-handler/index.js';
import { EventBus } from '../eventbus/event-bus.js';
import { ApprovalMachineController } from '../machines/approval-machine.js';
import { rehydrateRuns, RunRegistry } from '../machines/run-registry.js';
import { PolicyEngine } from '../policy/policy-engine.js';
import { ProjectionManager } from '../projection/index.js';
import { AckTracker, HotStateManager } from '../state/index.js';
import { BaselineTracker, FastGate, Integrator } from '../integrator/index.js';
import { WorktreeLifecycle } from '../run/index.js';
import { authMiddleware, generateAndSaveToken } from './auth.js';
import { registerRoutes } from './routes.js';
import { SettingsStore } from './settings-store.js';
import { SseManager } from './sse.js';
import { UiCommandService } from './ui-command-service.js';
import { UiQueryService } from './ui-query-service.js';

const DEFAULT_DEV_RUN_DURATION_MS = 3_000;

function createDevRunArtifact(prompt: string | undefined, worktreePath: string): void {
  if (!prompt || !/write|create|test file/i.test(prompt)) {
    return;
  }

  const filePath = path.join(worktreePath, 'src', 'generated-dev-run.test.ts');
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(
    filePath,
    [
      '// generated by /_dev/start-run',
      '// TODO: replace with a real test',
      'export const generatedDevRun = true;',
      '',
    ].join('\n'),
    'utf8',
  );
}

export interface StartHttpServerOptions {
  host?: string;
  isDevelopment?: boolean;
  logger?: FastifyServerOptions['logger'];
  memoryRepoBasePath?: string;
  policyCachePath?: string;
  policyPath?: string;
  port?: number;
  runDir?: string;
  sessionTokenPath?: string;
  stateDir?: string;
  soulConfigPath?: string;
  skipSignalHandlers?: boolean;
  worktreeBasePath?: string;
  workspaceRoot?: string;
}

export interface HttpServerHandle {
  app: FastifyInstance;
  coreSessionId: string;
  eventBus: EventBus;
  host: string;
  port: number;
  stateStore: StateStore;
  sseManager: SseManager;
  stop: () => Promise<void>;
  token: string;
}

function resolveBoundPort(app: FastifyInstance): number {
  const address = app.server.address();
  if (!address || typeof address === 'string') {
    throw new Error('Unable to resolve bound HTTP port');
  }

  return address.port;
}

export async function startHttpServer(
  options: StartHttpServerOptions = {},
): Promise<HttpServerHandle> {
  const tokenPath = options.sessionTokenPath ?? SESSION_TOKEN_PATH;
  const runDir = options.runDir ?? path.dirname(tokenPath);
  const stateDir = options.stateDir ?? STATE_DIR;
  const stateDbPath = path.join(stateDir, 'state.db');
  const soulDbPath = path.join(stateDir, 'soul.db');
  const memoryRepoBasePath =
    options.memoryRepoBasePath ?? path.join(path.dirname(stateDir), 'memory');
  const worktreeBasePath =
    options.worktreeBasePath ?? path.join(path.dirname(stateDir), 'worktrees');
  const workspaceRoot = options.workspaceRoot ?? process.cwd();
  const policyPath = options.policyPath ?? path.join(path.dirname(runDir), 'policy.json');
  const policyCachePath =
    options.policyCachePath ?? path.join(runDir, 'hook-policy-cache.json');
  ensureRuntimeDirs({
    runDir,
    stateDir,
  });

  const token = generateAndSaveToken(tokenPath);
  const coreSessionId = `core_sess_${Date.now()}_${randomUUID().slice(0, 8)}`;
  const workerClient = new WorkerClient(stateDbPath);
  const hotStateManager = new HotStateManager({
    dbPath: stateDbPath,
  });
  const approvalMachine = new ApprovalMachineController({
    dbWriter: workerClient,
    onDecision: (decision) => {
      hotStateManager.syncApprovalDecision({
        approval_id: decision.approvalId,
        approved: decision.approved,
        resolved_at: new Date().toISOString(),
        resolver:
          decision.status === 'timeout'
            ? 'timeout'
            : decision.approved
              ? 'policy'
              : 'user',
        status: decision.status,
      });
    },
  });
  const policyEngine = new PolicyEngine({
    approvalMachine,
    cachePath: policyCachePath,
    policyPath,
    workspaceRoot,
  });
  policyEngine.load();

  const ackTracker = new AckTracker();
  const sseManager = new SseManager({
    coreSessionId,
    resolveCause: (revision) => ackTracker.getCauseForRevision(revision),
  });
  const eventBus = new EventBus({
    workerClient,
  });
  eventBus.onAny((event) => {
    hotStateManager.apply(event);
  });
  await rehydrateRuns({
    dbPath: stateDbPath,
    dbWriter: workerClient,
    eventBus,
  });
  await hotStateManager.bootstrap();

  const worktreeManager = new WorktreeManager({
    baseDir: worktreeBasePath,
  });
  const baselineTracker = new BaselineTracker({
    dbPath: stateDbPath,
    dbWriter: workerClient,
  });
  const fastGate = new FastGate({
    baselineTracker,
  });
  let worktreeLifecycle: WorktreeLifecycle;
  const runRegistry = new RunRegistry({
    dbWriter: workerClient,
    eventBus,
    onStatusChange: async (event) => {
      hotStateManager.syncRunStatus({
        agent_id: event.agentId,
        engine_type: event.engineType,
        run_id: event.runId,
        status:
          event.status === 'created'
          || event.status === 'started'
          || event.status === 'running'
          || event.status === 'waiting_approval'
          || event.status === 'completed'
          || event.status === 'failed'
          || event.status === 'cancelled'
          || event.status === 'interrupted'
          || event.status === 'governance_invalid'
            ? event.status
            : 'running',
        updated_at: new Date().toISOString(),
        workspace_id: event.workspaceId,
      });
      await worktreeLifecycle.handleStatusChange({
        runId: event.runId,
        status: event.status,
        workspaceId: event.workspaceId,
      });
    },
    policyEvaluate: (toolName, args, context) =>
      policyEngine.evaluate(toolName, args, {
        runId: context.runId,
        workspaceRoot,
      }).result,
    source: 'core.run-registry',
  });
  const integrator = new Integrator({
    dbPath: stateDbPath,
    dbWriter: workerClient,
    eventBus,
    fastGate,
    governanceInvalidator: {
      invalidateRun: async (runId, reason) => {
        const invalidated = runRegistry.invalidateGovernance(runId, reason);
        if (invalidated) {
          return;
        }
        await workerClient.write({
          params: [new Date().toISOString(), new Date().toISOString(), runId],
          sql: `UPDATE runs
                SET status = 'governance_invalid',
                    updated_at = ?,
                    completed_at = ?
                WHERE run_id = ?`,
        });
        eventBus.publish({
          reason,
          runId,
          source: 'core.governance',
          status: 'governance_invalid',
          timestamp: new Date().toISOString(),
        });
      },
    },
    repoPath: workspaceRoot,
  });
  worktreeLifecycle = new WorktreeLifecycle({
    dbPath: stateDbPath,
    dbWriter: workerClient,
    integrator,
    repoPath: workspaceRoot,
    worktreeManager,
  });
  try {
    await worktreeLifecycle.cleanupOrphans([]);
  } catch (error) {
    console.warn('[core][http] skipped orphan worktree cleanup', error);
  }
  const soulToolDispatcher = createSoulToolDispatcher({
    configPath: options.soulConfigPath,
    dbPath: soulDbPath,
    eventSubscriber: eventBus,
    loadCompletedRun: async (runId) => {
      const db = createReadConnection(stateDbPath);
      try {
        const row = db
          .prepare(
            `SELECT workspace_id, metadata
             FROM runs
             WHERE run_id = ?`,
          )
          .get(runId) as
          | {
              metadata: string | null;
              workspace_id: string;
            }
          | undefined;
        if (!row) {
          return null;
        }

        const metadata = row.metadata
          ? (JSON.parse(row.metadata) as {
              branchName?: string;
              patch?: string;
            })
          : {};
        return {
          commitSha: metadata.branchName,
          diff: metadata.patch ?? '',
          projectId: row.workspace_id,
          runId,
        };
      } finally {
        db.close();
      }
    },
    memoryRepoBasePath,
    publishEvent: (event) => eventBus.publish(event),
    workspaceRoot,
  });
  const projectionManager = new ProjectionManager({
    definitions: {
      healing_stats_view: {
        load: async () => soulToolDispatcher.getHealingStats(),
        ttlMs: 5_000,
      },
      pending_soul_proposals: {
        load: async (scopeId) =>
          soulToolDispatcher.listPendingProposals(scopeId === '*' ? undefined : scopeId),
        ttlMs: 15_000,
      },
      run_history_agg: {
        load: async () => ({ runs: [] }),
        ttlMs: 30_000,
      },
    },
  });
  attachAsyncEventPath({
    eventBus,
    projectionManager,
    sseManager,
  });
  const eventDispatcher = new EventDispatcher({
    ackTracker,
    eventBus,
  });
  const hotStateStore = new StateStore(stateDbPath, hotStateManager);
  const settingsStore = new SettingsStore(workspaceRoot);
  const uiQueryService = new UiQueryService({
    coreSessionId,
    hotStateManager,
    settingsStore,
    soulDbPath,
    stateDbPath,
    workspaceRoot,
  });
  const uiCommandService = new UiCommandService({
    ackTracker,
    approvalMachine,
    eventBus,
    hotStateManager,
    mcpToolDispatcher: soulToolDispatcher,
    queryService: uiQueryService,
    runRegistry,
    settingsStore,
    stateDbPath,
    workerClient,
    workspaceRoot,
  });
  const app = Fastify({ logger: options.logger ?? true });
  const host = options.host ?? HOST;
  const requestedPort = options.port ?? PORT;
  const isDevelopment =
    options.isDevelopment ?? process.env.NODE_ENV === 'development';

  app.addHook(
    'onRequest',
    authMiddleware({
      skipPaths: new Set(['/health', '/internal/hook-event']),
      token,
    }),
  );

  registerRoutes(app, {
    ackTracker,
    commandService: uiCommandService,
    coreSessionId,
    eventDispatcher,
    isDevelopment,
    mcpToolDispatcher: soulToolDispatcher,
    projectionManager,
    queryService: uiQueryService,
    startDevRun: isDevelopment
      ? async (input) => {
          const runId = `run-${randomUUID()}`;
          const durationMs = Math.max(
            250,
            Math.min(input.durationMs ?? DEFAULT_DEV_RUN_DURATION_MS, 10_000),
          );
          const actor = runRegistry.create({
            engineType: input.engine ?? 'claude',
            runId,
            workspaceId: 'workspace-dev',
          });
          actor.send({ type: 'START' });

          try {
            const allocation = await worktreeLifecycle.ensureAllocated({
              runId,
              workspaceId: 'workspace-dev',
            });
            createDevRunArtifact(input.prompt, allocation.worktreePath);
            await runGit(['status', '--short'], {
              cwd: allocation.worktreePath,
            });

            setTimeout(() => {
              actor.send({ type: 'COMPLETE' });
              setTimeout(() => {
                runRegistry.destroyCompleted();
              }, 50);
            }, durationMs).unref();

            return {
              durationMs,
              runId,
              worktreePath: allocation.worktreePath,
            };
          } catch (error) {
            actor.send({
              error: error instanceof Error ? error.message : String(error),
              type: 'FAIL',
            });
            runRegistry.destroyCompleted();
            throw error;
          }
        }
        : undefined,
    stateStore: hotStateStore,
    sseManager,
    token,
  });

  await app.listen({ host, port: requestedPort });

  let stopping = false;
  const stop = async () => {
    if (stopping) {
      return;
    }
    stopping = true;

    await app.close();
    await runRegistry.stopAll();
    sseManager.closeAll();
    ackTracker.close();
    policyEngine.stop();
    approvalMachine.stop();
    hotStateStore.close();
    await soulToolDispatcher.close();
    await workerClient.close();
  };

  if (!options.skipSignalHandlers) {
    const shutdown = (signal: NodeJS.Signals) => {
      app.log.info({ signal }, 'received shutdown signal');
      void stop().finally(() => {
        process.exit(0);
      });
    };

    process.once('SIGINT', () => shutdown('SIGINT'));
    process.once('SIGTERM', () => shutdown('SIGTERM'));
  }

  return {
    app,
    coreSessionId,
    eventBus,
    host,
    port: resolveBoundPort(app),
    stateStore: hotStateStore,
    sseManager,
    stop,
    token,
  };
}
