import Fastify, { type FastifyInstance, type FastifyServerOptions } from 'fastify';
import { randomUUID } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { createSoulToolDispatcher } from '@do-what/soul';
import { runGit, WorktreeManager } from '@do-what/tools';
import {
  HOST,
  PORT,
  SESSION_TOKEN_PATH,
  STATE_DIR,
  ensureRuntimeDirs,
} from '../config.js';
import { StateStore } from '../db/state-store.js';
import { WorkerClient } from '../db/worker-client.js';
import { createReadConnection } from '../db/read-connection.js';
import { EventBus } from '../eventbus/event-bus.js';
import { ApprovalMachineController } from '../machines/approval-machine.js';
import { rehydrateRuns, RunRegistry } from '../machines/run-registry.js';
import { PolicyEngine } from '../policy/policy-engine.js';
import { BaselineTracker, FastGate, Integrator } from '../integrator/index.js';
import { WorktreeLifecycle } from '../run/index.js';
import { authMiddleware, generateAndSaveToken } from './auth.js';
import { registerRoutes } from './routes.js';
import { SseManager } from './sse.js';

const DEFAULT_DEV_RUN_DURATION_MS = 3_000;

function createDevRunArtifact(prompt: string | undefined, worktreePath: string): void {
  if (!prompt || !/write|create|test file/i.test(prompt)) {
    return;
  }

  const filePath = path.join(worktreePath, 'src', 'generated-dev-run.test.ts');
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(
    filePath,
    [
      '// generated by /_dev/start-run',
      '// TODO: replace with a real test',
      'export const generatedDevRun = true;',
      '',
    ].join('\n'),
    'utf8',
  );
}

export interface StartHttpServerOptions {
  host?: string;
  isDevelopment?: boolean;
  logger?: FastifyServerOptions['logger'];
  memoryRepoBasePath?: string;
  policyCachePath?: string;
  policyPath?: string;
  port?: number;
  runDir?: string;
  sessionTokenPath?: string;
  stateDir?: string;
  soulConfigPath?: string;
  skipSignalHandlers?: boolean;
  worktreeBasePath?: string;
  workspaceRoot?: string;
}

export interface HttpServerHandle {
  app: FastifyInstance;
  eventBus: EventBus;
  host: string;
  port: number;
  stateStore: StateStore;
  sseManager: SseManager;
  stop: () => Promise<void>;
  token: string;
}

function resolveBoundPort(app: FastifyInstance): number {
  const address = app.server.address();
  if (!address || typeof address === 'string') {
    throw new Error('Unable to resolve bound HTTP port');
  }

  return address.port;
}

export async function startHttpServer(
  options: StartHttpServerOptions = {},
): Promise<HttpServerHandle> {
  const tokenPath = options.sessionTokenPath ?? SESSION_TOKEN_PATH;
  const runDir = options.runDir ?? path.dirname(tokenPath);
  const stateDir = options.stateDir ?? STATE_DIR;
  const stateDbPath = path.join(stateDir, 'state.db');
  const memoryRepoBasePath =
    options.memoryRepoBasePath ?? path.join(path.dirname(stateDir), 'memory');
  const worktreeBasePath =
    options.worktreeBasePath ?? path.join(path.dirname(stateDir), 'worktrees');
  const workspaceRoot = options.workspaceRoot ?? process.cwd();
  const policyPath = options.policyPath ?? path.join(path.dirname(runDir), 'policy.json');
  const policyCachePath =
    options.policyCachePath ?? path.join(runDir, 'hook-policy-cache.json');
  ensureRuntimeDirs({
    runDir,
    stateDir,
  });

  const token = generateAndSaveToken(tokenPath);
  const workerClient = new WorkerClient(stateDbPath);
  const approvalMachine = new ApprovalMachineController({
    dbWriter: workerClient,
  });
  const policyEngine = new PolicyEngine({
    approvalMachine,
    cachePath: policyCachePath,
    policyPath,
    workspaceRoot,
  });
  policyEngine.load();

  const sseManager = new SseManager();
  const eventBus = new EventBus({
    sseManager,
    workerClient,
  });
  await rehydrateRuns({
    dbPath: stateDbPath,
    dbWriter: workerClient,
    eventBus,
  });

  const worktreeManager = new WorktreeManager({
    baseDir: worktreeBasePath,
  });
  const baselineTracker = new BaselineTracker({
    dbPath: stateDbPath,
    dbWriter: workerClient,
  });
  const fastGate = new FastGate({
    baselineTracker,
  });
  const integrator = new Integrator({
    dbPath: stateDbPath,
    dbWriter: workerClient,
    eventBus,
    fastGate,
    repoPath: workspaceRoot,
  });
  const worktreeLifecycle = new WorktreeLifecycle({
    dbPath: stateDbPath,
    dbWriter: workerClient,
    integrator,
    repoPath: workspaceRoot,
    worktreeManager,
  });
  try {
    await worktreeLifecycle.cleanupOrphans([]);
  } catch (error) {
    console.warn('[core][http] skipped orphan worktree cleanup', error);
  }
  const runRegistry = new RunRegistry({
    dbWriter: workerClient,
    eventBus,
    onStatusChange: async (event) => {
      await worktreeLifecycle.handleStatusChange({
        runId: event.runId,
        status: event.status,
        workspaceId: event.workspaceId,
      });
    },
    policyEvaluate: (toolName, args, context) =>
      policyEngine.evaluate(toolName, args, {
        runId: context.runId,
        workspaceRoot,
      }).result,
    source: 'core.run-registry',
  });
  const soulToolDispatcher = createSoulToolDispatcher({
    configPath: options.soulConfigPath,
    dbPath: path.join(stateDir, 'soul.db'),
    eventSubscriber: eventBus,
    loadCompletedRun: async (runId) => {
      const db = createReadConnection(stateDbPath);
      try {
        const row = db
          .prepare(
            `SELECT workspace_id, metadata
             FROM runs
             WHERE run_id = ?`,
          )
          .get(runId) as
          | {
              metadata: string | null;
              workspace_id: string;
            }
          | undefined;
        if (!row) {
          return null;
        }

        const metadata = row.metadata
          ? (JSON.parse(row.metadata) as {
              branchName?: string;
              patch?: string;
            })
          : {};
        return {
          commitSha: metadata.branchName,
          diff: metadata.patch ?? '',
          projectId: row.workspace_id,
          runId,
        };
      } finally {
        db.close();
      }
    },
    memoryRepoBasePath,
    publishEvent: (event) => eventBus.publish(event),
    workspaceRoot,
  });
  const stateStore = new StateStore(stateDbPath);
  const app = Fastify({ logger: options.logger ?? true });
  const host = options.host ?? HOST;
  const requestedPort = options.port ?? PORT;
  const isDevelopment =
    options.isDevelopment ?? process.env.NODE_ENV === 'development';

  app.addHook(
    'onRequest',
    authMiddleware({
      skipPaths: new Set(['/health', '/internal/hook-event']),
      token,
    }),
  );

  registerRoutes(app, {
    eventBus,
    isDevelopment,
    mcpToolDispatcher: soulToolDispatcher,
    startDevRun: isDevelopment
      ? async (input) => {
          const runId = `run-${randomUUID()}`;
          const durationMs = Math.max(
            250,
            Math.min(input.durationMs ?? DEFAULT_DEV_RUN_DURATION_MS, 10_000),
          );
          const actor = runRegistry.create({
            engineType: input.engine ?? 'claude',
            runId,
            workspaceId: 'workspace-dev',
          });
          actor.send({ type: 'START' });

          try {
            const allocation = await worktreeLifecycle.ensureAllocated({
              runId,
              workspaceId: 'workspace-dev',
            });
            createDevRunArtifact(input.prompt, allocation.worktreePath);
            await runGit(['status', '--short'], {
              cwd: allocation.worktreePath,
            });

            setTimeout(() => {
              actor.send({ type: 'COMPLETE' });
              setTimeout(() => {
                runRegistry.destroyCompleted();
              }, 50);
            }, durationMs).unref();

            return {
              durationMs,
              runId,
              worktreePath: allocation.worktreePath,
            };
          } catch (error) {
            actor.send({
              error: error instanceof Error ? error.message : String(error),
              type: 'FAIL',
            });
            runRegistry.destroyCompleted();
            throw error;
          }
        }
        : undefined,
    stateStore,
    sseManager,
    token,
  });

  await app.listen({ host, port: requestedPort });

  let stopping = false;
  const stop = async () => {
    if (stopping) {
      return;
    }
    stopping = true;

    await app.close();
    runRegistry.stopAll();
    sseManager.closeAll();
    policyEngine.stop();
    approvalMachine.stop();
    stateStore.close();
    await soulToolDispatcher.close();
    await workerClient.close();
  };

  if (!options.skipSignalHandlers) {
    const shutdown = (signal: NodeJS.Signals) => {
      app.log.info({ signal }, 'received shutdown signal');
      void stop().finally(() => {
        process.exit(0);
      });
    };

    process.once('SIGINT', () => shutdown('SIGINT'));
    process.once('SIGTERM', () => shutdown('SIGTERM'));
  }

  return {
    app,
    eventBus,
    host,
    port: resolveBoundPort(app),
    stateStore,
    sseManager,
    stop,
    token,
  };
}
